### ISSUE TITLE
Timestamps 

### ISSUE THREAD

**Issue by Spillis** [Icecrown-Community/ICC-Member-Website-Public#108]
A way to track and look up when someone added a customer. Currently there seemse to be no way to know who out of 40938 adverts fucked up and over booked making it imposible for me to talk with that person and looking what's up.

**Comment by Bgabor997** [comment]
@iElsha can we maybe add a simple timestamp at the footer of the booking, i think its about 10-15min and would help a lot to Gold Collectors and Advertisers

**Comment by Winchester-Icc** [comment]
As the curve is over, or full rather, Im coming to bring this exact topic as it's hotter than our hot deals. I had something else in mind which is way more complicated to implement anyway, but simple timestamp will do the job. As a GC sometimes I have to push people back in next run due to overbooking and I don't really know every time who's been booked last as customers are pepega and eat up almost all of your time sometimes. So yeah if I knew whos last I could just skip him and deal with it as soon as I'm done preparing the particular run and deal with the overbook right after - instead I have to investigate and lose precious time and delay the run potentially because all advertisers are like "I was first" or " It wasn't me".

As an advertiser myself, I try my fkin best to not overbook and yet I still get asked to move my customer back which I do but it's really annoying especially when I'm completely sure mine was fine as I refreshed twice after booking him and bookings were full but not over.  I have to do Screenshots of the booking page in order to prove my booking wasn't over the limit.

ps: I have bound F5 on my side mouse buttons and I spam the shit out of it, but I feel some people either CBA to refresh. Or maybe they are still new in this and they obv don't do it on purpose. Might not even realise what they do, so we can let them know.
![F5](https://user-images.githubusercontent.com/77925888/110509635-fbdaab00-810a-11eb-842f-3397f869155d.png)

**Comment by Dejnaa** [comment]
> @iElsha can we maybe add a simple timestamp at the footer of the booking, i think its about 10-15min and would help a lot to Gold Collectors and Advertisers

Yes please

**Comment by iElsha** [comment]
I am not sure we need timestamp as they are already ordered from older (updated or not) to most recent

**Comment by Bgabor997** [comment]
for curve shifts we reorder it, we sort it by the booking's time, and the timestamps would be usefull to know which advertiser overbooked, and we need to move that booking

I have this too in the stash i mentioned u, it was 2 minutes

**Comment by iElsha** [comment]
![image](https://user-images.githubusercontent.com/38140638/114513581-a1b59400-9c3a-11eb-9a89-b0ea3afcffae.png)

This is how the sorting works and as show we don't need a timestamp as the position of the bookings will be :
- Shiffted -> Sort by Shift, present oldest (of this shift) to most recent (of this shift) and this for each shift
- Non Shiffted -> No sort, it's displayed oldest to most recent (updates doesn't change anything)

**Comment by Wanhedaa** [comment]
> ![image](https://user-images.githubusercontent.com/38140638/114513581-a1b59400-9c3a-11eb-9a89-b0ea3afcffae.png)
> 
> This is how the sorting works and as show we don't need a timestamp as the position of the bookings will be :
> - Shiffted -> Sort by Shift, present oldest (of this shift) to most recent (of this shift) and this for each shift
> - Non Shiffted -> No sort, it's displayed oldest to most recent (updates doesn't change anything)


At curve runs we have to do like this:

xx:00 /xx:30 - > SLG/SLG + sire
xx:15 / xx:45 - > Sire only

It helps us to inform the customer correctly, we GC-s can see cleaner who we need to invite. But due to the slg+sire and sire are at 2 different time, we need timestamp on it to know, if someone ninja booked an slg+ sire customer, or the sire was overbooking.

It's a really old problem, and it's hard to tell the advertiser, that sorry, we can't take your sire customer cuz it's an overbooking, even tho it was maybe booked a hour before, and an slg+sire got his spot.

This is a really old problem, and we all want this timestamp on it.

**Comment by Wanhedaa** [comment]
![image](https://user-images.githubusercontent.com/77633500/128631260-4381f0a8-ebe0-4b0f-9f57-e6398ce44ad2.png)
it is still a problem. We had 6 sylvanas  booked while we take 5 and i don't know if the last 2 bosses or the last boss was booked later 🤷

**Comment by disstressed** [comment]
Tbh the easiest solution would be adding 2 new componenents below the GC note, 
one for booking created at : Gets server time , add's it down there when the new component is created for the booking
booking edited at : Don't think it's needed, but yea
It would still couse some issues due manually looking up the times, however, it's better then nothing.

**Comment by Bgabor997** [comment]
This is already done guys, but its not on the current prio list, btw its rdy to deploy.
