### ISSUE TITLE
Mandatory Note Field

### ISSUE THREAD

**Issue by IndigoICC** [Icecrown-Community/ICC-Member-Website-Public#137]
As VIPs will be extremely lucrative this tier compared to the last; we need the Mandatory function added to the booster note. 

![image](https://user-images.githubusercontent.com/77749513/129411160-09abed6c-e801-458b-b7e8-1f6d6394faa4.png)

**Comment by Dejnaa** [comment]
@IndigoICC What would the purpose be of this note?
Would it be better if boosters had to press what specc they boost as on each char? (fex feral druid, holy pala ect)

**Comment by Dejnaa** [comment]
I asked Indigo in DMs since I dont know if he still has access here.

Point of this note is for raidleads to be able to have a clear vision which boosters can trade items, and not having to DM to ask boosters who have a blank note with each raid. 

Would speed up the process of checking VIP availability based on signups - in future maybe that could also be integrated with a visible VIP count for advertisers.

@Bgabor997 how much work would it take to make the NOTE a mandatory field? :)

**Comment by Dejnaa** [comment]
@Papa2324 please add severity

**Comment by Papa2324** [comment]
@Bgabor997 * another one * <3

**Comment by Bgabor997** [comment]
we have something for this in our mind :) coming soon

**Comment by Bgabor997** [comment]
implemented and deployed today
