### ISSUE TITLE
Change M+ Default: "No specific key" to "Random key"

### ISSUE THREAD

**Issue by Highlifez** [Icecrown-Community/ICC-Member-Website-Public#148]
So currently "No specific key" apparently means the customer is fielding the key. And "Random key" means the boosters have to field one. As it currently stands, the customer rarely wants to do their own key, therefore "Random key" is the most used option and should be the default. Please change.

Also, maybe change "No specific key" to "Customers key", since per definition 'non specific' and 'random' quite literally means the same thing. Leads to unnecessary confusion. 
Thanks, Highlife

**Comment by Wanhedaa** [comment]
> that the adv doesn't want the keystone button on it.

This is not true. If we advertisers take whatever key is needed (so a random key) we choose random key (that's why we have keystone there), so if someone wants to sacrefice their key, they can click on the keystone icon. If it's no specific key, we use the customer's key and add in the note what key is it.  

If we use no specific key for "whatever key is it" then we will sit front of the customer with 4x 23s keys and noone will lower their key. This is why random key exists.

**Comment by iElsha** [comment]
So it would be better to rename the "No Specific Key" option to customer key?

**Comment by Highlifez** [comment]
I think that would be the best course of action, yeah. Also solves any confusions as to what the difference between the two is.

**Comment by Dejnaa** [comment]
@iElsha could you assign someone to make this change since its a "Fast Update"?

**Comment by Highlifez** [comment]
Can we please get these two changes through? It's especially annyoing trying to explain what No specific key even means to the new trainees. Thank you very much!

1) Change "Random key" to be the default choice
2) Change "No specific key" to "Customer Key"

**Comment by Bgabor997** [comment]
implemented and deployed 2021.10.14
