### ISSUE TITLE
Forcing to add discord tag / battlenet of the customer

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/ICC-Member-Website-Public#152]
From my experience (as i take most of the curves so i know 90% of the advertisers bookings) i would say, forcing to add discord tag is not needed.

Only a few of the advertisers give the real discord tag of the customers ( i assume mostly ticket customers), the others just put their owns or just a space.

I think forcing it is just timewaste for the big hyper advertisers who book 2-3 customers / 2mins. If anyone wants to use the discord tag, they will add it anyway. They always did.

**Comment by Phenthex** [comment]
I aggree and disagree on this one.

It is a timewaste for giga advertisers for example when he/she is filling the curve yeah, but i didnt know they can press space and still able to book. So if they are booking with a space button it turns out not a timewaste really simple and easy. Just a space button.

Also some cases we really need customer's discord or battletag. If the advertiser not around and if the customer wont show up at the time, we can reach them with their ids -as gc-
So this topic still a dilemma for me.

**Comment by Wanhedaa** [comment]
>  If the advertiser not around and if the customer wont show up at the time, we can reach them with their ids -as gc-

Even if we force them to add their discord tag there, they don't do it. I just had a case last night where the advertiser went to sleep, the customer was offline, and the advertiser gave his own discord tag :KekW: 

If anyone wants to use it, he will use it properly, just like before, without him being forced to do it

**Comment by Phenthex** [comment]
Well that also makes sense. Personally im always adding customer's discord instead of mine. But forcing advertisers into this, if this makes them to be cba and type their own discord yeah doesn't make any sense. We will still searching customer everywhere if advertiser is offline. So better to not have this as mandatory for bookings then.

Agree this time you changed my mind 😄 If anyone want to add customer's discord or battlenet there they already will yeah.

**Comment by Bgabor997** [comment]
We will remove the forcing from curve raids

**Comment by Bgabor997** [comment]
implemented and deployed 2021.10.14
