### ISSUE TITLE
Prevent selected booster to remove his signup

### ISSUE THREAD

**Issue by IndigoICC** [Icecrown-Community/ICC-Member-Website-Public#39]
The Raid Leaders have had a few issues with boosters un-signing after they've been picked for the setup without notifying the Raid Leader. It would be really helpful if the assigned Raid Leader for the Boost could get a DM from Gluth, notifying them about this.

**Comment by iElsha** [comment]
Do you mean that once the booster is selected in the roster, the guy removed his participation?

If so that shouldn’t happen has the raid should be in the running step but we figured out, it was not perfect at the beginning. This is more a bug here because if the guy is in the roster he shouldn’t be allowed to sign out and needs to ask to the raid leader.

After asking the raid leader will handle the matter and might take any actions if needed.

**Comment by IndigoICC** [comment]
Pardon the late response
Raid Leaders usually start picking their setup rather early, up to 2 days before the run actually is supposed to happen - Raid leaders will swap between Running and Open if they do not have enough sign ups. Once swapped back to Open; boosters will then unsign, even if picked.

**Comment by iElsha** [comment]
Alright, I understood better but it's still a bug, high prio or medium prio for the RL team @IndigoICC ?

**Comment by IndigoICC** [comment]
Medium prio

**Comment by ICCDesi** [comment]
@iElsha @IndigoICC 

I'd say don't Prevent them from removing their sign-ups. Something might happen to them so they have to. You can set it as:

1)They can't remove sign-uns before 2-3 hours of the raid.
2)RL gets informed about that removal.

**Comment by IndigoICC** [comment]
The prevention should not be there no; it's mainly the RL's being informed ye ^
