### ISSUE TITLE
Not informing the customer about the new gold collector

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/ICC-Member-Website-Public#56]
If someone gives the customer's discord tag, the customer gets a message, where it says who will be the gold collector, so he can contact with the GC on discord. 

If someone can't attend on a day to collect the gold, the gold collector will be swapped to an another gold collector, but the customer is not notified about that, so he still thinks, the original gc will be his collector.

This happend to Venshroud, he dmed me about collecting his own run, but Choppa already swapped me to Dejna for a day. 

Yes, Ven could check it on the web, but if it would be a normal casual customer, he couldnt check it on the web.

Suggestion: notify the customer about changing the assigned GC on discord, if his name is given. ![unknown-11.png](https://user-images.githubusercontent.com/77633500/105609120-64620880-5da7-11eb-86b6-af101320a990.png)

**Comment by iElsha** [comment]
Perfect, just added it

**Comment by Dejnaa** [comment]
Dont know if we want - but maybe we should add the name of the alts somewhere? Could be our personal website settings

For Example, discord: Dejnaa [Adv manager] - ingame: Iccgcdejnaa 
From what i know the gold collectors name their alts the same on each realm?

So in the discord message it could link the discord tagg like it does, but instead of writing Discord name, to write the submitted alt name.

@Wanhedaa what do you think about that?

**Comment by iElsha** [comment]
@IndigoICC rework
